### ISSUE TITLE
example profile generates errors

### ISSUE THREAD

**Issue by windy54** [KenT2/pipresents-next#44]
Hi,
I have just installed pipresents-next on a raspberry PI B3 using the latest raspbian release.

when I follow the instructions and execute
python pipresents/pipresents.py -p pp_mediashow_1p2
the presentation runs but eventually generates the following errors

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1535, in __call__
    return self.func(*args)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 586, in callit
    func(*args)
  File "/home/pi/pipresents/pp_audioplayer.py", line 336, in play_state_machine
    self.end('normal','mplayer dead')
  File "/home/pi/pipresents/pp_audioplayer.py", line 401, in end
    self.end_callback('normal',"track has terminated or quit")
  File "/home/pi/pipresents/pp_mediashow.py", line 677, in end_player
    self.what_next()
  File "/home/pi/pipresents/pp_mediashow.py", line 496, in what_next
    self.play_selected_track(self.medialist.selected_track())
  File "/home/pi/pipresents/pp_mediashow.py", line 567, in play_selected_track
    enable_menu=self.enable_child)
  File "/home/pi/pipresents/pp_browserplayer.py", line 168, in play
    self.start_play_state_machine()
  File "/home/pi/pipresents/pp_browserplayer.py", line 250, in start_play_state_machine
    self.bplayer.play(self.track,self.geometry)
  File "/home/pi/pipresents/pp_uzbldriver.py", line 75, in play
    self._process = pexpect.spawn(cmd)
  File "/usr/local/lib/python2.7/dist-packages/pexpect.py", line 429, in __init__
    self._spawn (command, args)
  File "/usr/local/lib/python2.7/dist-packages/pexpect.py", line 516, in _spawn
    raise ExceptionPexpect ('The command was not found or was not executable: %s.' % self.command)
ExceptionPexpect: The command was not found or was not executable: uzbl-browser.

The error seems to be generated when the music stops and a slide showing a lake, with trees and text with Web Pages etc displayed. The slide show then stops, I am not sure if this is by design or due to the error.

I will investigate further and try my own profiles as this could be just what my local school is after.

cheers

Steve

**Comment by KenT2** [comment]
looks like you forgot to install uzbl browser

**Comment by windy54** [comment]
oops!
That is what happens when you try an install software with the football on TV.

apologies, all works
